Feedback crud
dtugroupd/RoomLocatorWebapp pull request #37
Opened 2019-11-01 06:30 UTC by Hamed-kad

2019-11-04 19:02 UTC, algorythm commented
Du har merge conflicts

2019-11-12 18:19 UTC, algorythm requested changes
Din kode kan ikke builde

2019-11-12 18:19 UTC, algorythm commented on src/app/components/status-button-menu/status-button-menu.component.ts
> +   //@Output()
Slet hellere i stedet for at udkommentere

2019-11-12 18:19 UTC, algorythm commented on src/app/components/status-button-menu/status-button-menu.component.ts
> +    //dispatch med en action eller array af action som man vil udløse(trigger)
hvor hører denne kommentar til?

2019-11-12 18:19 UTC, algorythm commented on src/app/router.state.ts
> +/* @State<boolean>({
Hellere slet i stedet for at have udkommenteret kode der ikke bliver brugt

2019-11-12 18:19 UTC, algorythm commented on src/app/app.state.ts
> +/*  @State<AppStateModel>({
Hellere slet kode i stedet for udkommenteret kode der ikke bliver brugt

2019-11-12 18:19 UTC, algorythm commented on src/app/_services/feedback.service.ts
> +  // DET SKAL VÆRE HTTPClient.Post ISTEDET
Hvad mener du?

2019-11-12 18:19 UTC, algorythm commented on src/app/app.state.ts
> +    feedback: boolean;
Bruger du overhovedet det her nogle steder? Hvis nej, så slet gerne hele filen

2019-11-14 12:05 UTC, algorythm commented
Build fejler

2019-11-14 13:35 UTC, Hamed-kad commented
De ændringer er lavet,,

2019-11-14 13:55 UTC, algorythm commented
> De ændringer er lavet,,

Det kan jeg jo se her på Github de ikke er. Ellers har du glemt at pushe

2019-11-20 15:43 UTC, closed without merging