Use old CampusNet Login
dtugroupd/RoomLocatorWebapp pull request #70
Opened 2019-11-22 15:04 UTC by algorythm

2019-11-25 00:10 UTC, Hudhud requested changes

2019-11-25 00:10 UTC, Hudhud commented on src/app/_services/auth.service.ts
> +  // }
Hvad er formålet med denne funktion? Den er jo bare tom

2019-11-25 13:03 UTC, Hudhud requested changes

2019-11-25 13:03 UTC, Hudhud commented on src/app/models/login/user.model.ts
> +    password: string;
Problemet ved at sætte koden som blot en string er, at selve koden vil blive fremvist i konsollen for den pågældende payload. Der vil komme til at stå: {username: "sXXXXXX", password: "MINKODE"}

2019-11-26 13:57 UTC, algorythm commented on src/app/models/login/user.model.ts
> +    password: string;
Det er kun development. Jeg er jo nødt til at sende koden til backenden for at kunne logge brugeren ind

2019-11-26 13:57 UTC, algorythm commented on src/app/_services/auth.service.ts
> +  // }
ja jeg skal lige have ryttet op her. Det er gammel logik som jeg har rykket rundt.

2019-11-26 14:46 UTC, Hudhud requested changes

2019-11-26 14:46 UTC, Hudhud commented on src/app/auth/validate/validate.component.ts
> + * @author Anders Wiberg Olsen, s165241
Author tags står allerede i toppen af filen - Dit navn står der allerede.

2019-11-26 14:54 UTC, Hudhud approved these changes

2019-11-26 14:54 UTC, merged